### ISSUE TITLE
Comparion of your result with other paper

### ISSUE THREAD

**Issue by chenxiangzZ** [hh23333/PVPM#13]
in your paper
![image](https://user-images.githubusercontent.com/30611183/94632695-de084f00-02fd-11eb-896e-bd2401f40cc3.png)
in cvpr2020‘s other paper,named "High-Order Information Matters: Learning Relation and Topology
for Occluded Person Re-Identification’
![image](https://user-images.githubusercontent.com/30611183/94632888-54a54c80-02fe-11eb-82ae-565b1d16028c.png)
the two result on Occluded-REID，has large differences in PCB and much gap in the final result , i m curious aboult this ,could you please give me a detailed reason.

**Comment by hh23333** [comment]
1. About the PCB baseline, I think we used the same evaluation criteria, and I am not very clear why the result of this article is so low.
2. For the final result, HOReID is a very good work, and achieves much better than ours. However, part of the high results are due to the use of more components, such as triplet loss and combination of the global branch. Also need to mention, HOReid need to interact within each image pair, which leads to low computational efficiency
