### ISSUE TITLE
关于数据集测试

### ISSUE THREAD

**Issue by liqi-lizezhong** [hh23333/PVPM#2]
您好，我们对您的论文内容非常感兴趣，并通过您上传的代码进行实现，发现了一些问题，想问您一些关于数据的一些细节，比如通过openpose得到的数据集关键点特征图是多少个通道的图像呢，我看您代码实现中是通过读取png的方式实现的关键点特征读取，另外关于这点，为什么关键点特征的输入通道是56，这是根据PNG通道层数设置的吗？

**Comment by hh23333** [comment]
openpose的输出结果我们存成了png的格式(单通道height*(width*56))，运行/scripts/openpose_*.sh文件可以得到，56个通道是18个keypoint map加38个paf结果，使用的时候我们就是把读取的png reshape了一下




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            高尚
                            
                            
                                
                                    邮箱：gs940601k@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2020年04月28日 16:31，李泽中 写道： 
您好，我们对您的论文内容非常感兴趣，并通过您上传的代码进行实现，发现了一些问题，想问您一些关于数据的一些细节，比如通过openpose得到的数据集关键点特征图是多少个通道的图像呢，我看您代码实现中是通过读取png的方式实现的关键点特征读取，另外关于这点，为什么关键点特征的输入通道是56，这是根据PNG通道层数设置的吗？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/hh23333/PVPM/issues/2",
"url": "https://github.com/hh23333/PVPM/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hh23333** [comment]
@liqi-lizezhong 
您好，openpose的输出结果我们存成了png的格式(单通道height*(width*56))，就是把openpose输出结果平铺了一下，56个通道是18个keypoint map加38个paf结果，运行/scripts/openpose_*.sh文件可以得到，使用的时候我们就是把读取的png reshape了一下又变成了56通道

**Comment by liqi-lizezhong** [comment]
好的，明白了，谢谢您
